"""initial_schema

Revision ID: d691f9752240
Revises: 
Create Date: 2026-10-07 02:11:26.848895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'd691f9752240'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=100), nullable=False),
    sa.Column('rule_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_rules_id'), 'business_rules', ['id'], unique=False)
    op.create_index(op.f('ix_business_rules_rule_key'), 'business_rules', ['rule_key'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('inflow_actual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outflow_actual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_cash_flow', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_receivables', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_cash_buffer', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('liquidity_gap', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_cash_flows_company_date')
    )
    op.create_index(op.f('ix_cash_flows_company_id'), 'cash_flows', ['company_id'], unique=False)
    op.create_index(op.f('ix_cash_flows_created_at'), 'cash_flows', ['created_at'], unique=False)
    op.create_index(op.f('ix_cash_flows_date'), 'cash_flows', ['date'], unique=False)
    op.create_index(op.f('ix_cash_flows_id'), 'cash_flows', ['id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('expected_inflow', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_outflow', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_liquidity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('liquidity_gap', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('HEALTHY', 'WATCH', 'URGENT')", name='ck_forecasts_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_company_id'), 'forecasts', ['company_id'], unique=False)
    op.create_index(op.f('ix_forecasts_created_at'), 'forecasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_forecasts_forecast_date'), 'forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecasts_horizon_days'), 'forecasts', ['horizon_days'], unique=False)
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_forecasts_status'), 'forecasts', ['status'], unique=False)
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('ifsc_code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index(op.f('ix_suppliers_company_id'), 'suppliers', ['company_id'], unique=False)
    op.create_index(op.f('ix_suppliers_created_at'), 'suppliers', ['created_at'], unique=False)
    op.create_index(op.f('ix_suppliers_is_active'), 'suppliers', ['is_active'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'finance_manager', 'analyst')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('buyers',
    sa.Column('buyer_id', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('primary_supplier_id', sa.String(length=50), nullable=True),
    sa.Column('behavioural_segment', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount_responsiveness', sa.Float(), nullable=True),
    sa.Column('blacklisted', sa.Boolean(), nullable=False),
    sa.Column('disputed_flag', sa.Boolean(), nullable=False),
    sa.Column('first_invoice_date', sa.Date(), nullable=True),
    sa.Column('last_invoice_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("tier IS NULL OR tier IN ('A', 'B', 'C')", name='ck_buyers_tier'),
    sa.ForeignKeyConstraint(['primary_supplier_id'], ['suppliers.supplier_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('buyer_id')
    )
    op.create_index(op.f('ix_buyers_blacklisted'), 'buyers', ['blacklisted'], unique=False)
    op.create_index(op.f('ix_buyers_buyer_id'), 'buyers', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyers_created_at'), 'buyers', ['created_at'], unique=False)
    op.create_index(op.f('ix_buyers_disputed_flag'), 'buyers', ['disputed_flag'], unique=False)
    op.create_index(op.f('ix_buyers_primary_supplier_id'), 'buyers', ['primary_supplier_id'], unique=False)
    op.create_index(op.f('ix_buyers_tier'), 'buyers', ['tier'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("document_type IN ('policy', 'contract', 'sop')", name='ck_documents_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_active_status'), 'documents', ['active_status'], unique=False)
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_document_name'), 'documents', ['document_name'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_created_at'), 'document_chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('invoice_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('disputed', sa.Boolean(), nullable=False),
    sa.Column('invoice_status', sa.String(length=50), nullable=False),
    sa.Column('settled_date', sa.Date(), nullable=True),
    sa.Column('days_late', sa.Integer(), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("invoice_status IN ('open', 'settled')", name='ck_invoices_status'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.buyer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_invoices_buyer_id'), 'invoices', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_disputed'), 'invoices', ['disputed'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_id'), 'invoices', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_status'), 'invoices', ['invoice_status'], unique=False)
    op.create_index(op.f('ix_invoices_supplier_id'), 'invoices', ['supplier_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.String(length=50), nullable=False),
    sa.Column('payment_reliability', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('financial_risk', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('liquidity_risk', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overall_risk', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tier IS NULL OR tier IN ('A', 'B', 'C')", name='ck_risk_scores_tier'),
    sa.CheckConstraint('financial_risk >= 0 AND financial_risk <= 100', name='ck_risk_scores_financial_risk'),
    sa.CheckConstraint('liquidity_risk >= 0 AND liquidity_risk <= 100', name='ck_risk_scores_liquidity_risk'),
    sa.CheckConstraint('overall_risk >= 0 AND overall_risk <= 100', name='ck_risk_scores_overall_risk'),
    sa.CheckConstraint('payment_reliability >= 0 AND payment_reliability <= 100', name='ck_risk_scores_payment_reliability'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.buyer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_buyer_id'), 'risk_scores', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_computed_at'), 'risk_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_created_at'), 'risk_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    op.create_index(op.f('ix_risk_scores_tier'), 'risk_scores', ['tier'], unique=False)
    op.create_table('discount_offers',
    sa.Column('offer_id', sa.String(length=100), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.String(length=50), nullable=False),
    sa.Column('offer_date', sa.Date(), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=False),
    sa.Column('offered_rate_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_payable_if_accepted', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('days_accelerated', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recommended_by', sa.String(length=100), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('recommendation_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('recommended', 'offered', 'accepted', 'declined', 'expired', 'rejected')", name='ck_discount_offers_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.buyer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_index(op.f('ix_discount_offers_approved_by'), 'discount_offers', ['approved_by'], unique=False)
    op.create_index(op.f('ix_discount_offers_buyer_id'), 'discount_offers', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_discount_offers_created_at'), 'discount_offers', ['created_at'], unique=False)
    op.create_index(op.f('ix_discount_offers_deadline_date'), 'discount_offers', ['deadline_date'], unique=False)
    op.create_index(op.f('ix_discount_offers_invoice_id'), 'discount_offers', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_discount_offers_offer_date'), 'discount_offers', ['offer_date'], unique=False)
    op.create_index(op.f('ix_discount_offers_offer_id'), 'discount_offers', ['offer_id'], unique=False)
    op.create_index(op.f('ix_discount_offers_status'), 'discount_offers', ['status'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('late_probability', sa.Float(), nullable=False),
    sa.Column('predicted_days_late', sa.Integer(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('late_probability >= 0.0 AND late_probability <= 1.0', name='ck_model_predictions_late_prob'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_predictions_created_at'), 'model_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_predictions_id'), 'model_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_model_predictions_invoice_id'), 'model_predictions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_model_predictions_predicted_at'), 'model_predictions', ['predicted_at'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('discount_applied', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('completed', 'pending', 'failed', 'refunded')", name='ck_payments_status'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('settled', 'pending', 'failed')", name='ck_transactions_status'),
    sa.CheckConstraint("transaction_type IN ('credit', 'debit')", name='ck_transactions_type'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_payment_id'), 'transactions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_model_predictions_predicted_at'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_invoice_id'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_id'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_created_at'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_discount_offers_status'), table_name='discount_offers')
    op.drop_index(op.f('ix_discount_offers_offer_id'), table_name='discount_offers')
    op.drop_index(op.f('ix_discount_offers_offer_date'), table_name='discount_offers')
    op.drop_index(op.f('ix_discount_offers_invoice_id'), table_name='discount_offers')
    op.drop_index(op.f('ix_discount_offers_deadline_date'), table_name='discount_offers')
    op.drop_index(op.f('ix_discount_offers_created_at'), table_name='discount_offers')
    op.drop_index(op.f('ix_discount_offers_buyer_id'), table_name='discount_offers')
    op.drop_index(op.f('ix_discount_offers_approved_by'), table_name='discount_offers')
    op.drop_table('discount_offers')
    op.drop_index(op.f('ix_risk_scores_tier'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_created_at'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_computed_at'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_buyer_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_invoices_supplier_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_disputed'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_buyer_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_created_at'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_active_status'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_buyers_tier'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_primary_supplier_id'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_disputed_flag'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_created_at'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_buyer_id'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_blacklisted'), table_name='buyers')
    op.drop_table('buyers')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_is_active'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_created_at'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_company_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_forecasts_status'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_horizon_days'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_date'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_created_at'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_company_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_cash_flows_id'), table_name='cash_flows')
    op.drop_index(op.f('ix_cash_flows_date'), table_name='cash_flows')
    op.drop_index(op.f('ix_cash_flows_created_at'), table_name='cash_flows')
    op.drop_index(op.f('ix_cash_flows_company_id'), table_name='cash_flows')
    op.drop_table('cash_flows')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_business_rules_rule_key'), table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_id'), table_name='business_rules')
    op.drop_table('business_rules')
    # ### end Alembic commands ###
