import csv
import json
from pathlib import Path


SOURCE_FILE = Path("source_data/discount_offers_clean.csv")
OUTPUT_FILE = Path("seed_data/discount_offers.csv")

DATA_ORIGIN = "SIMULATED_DEMONSTRATION_OFFER_HISTORY"


def rate(value):
    return float(value or 0)


def amount(value):
    return float(value or 0)


def check_policy(row):
    violations = []

    invoice_amount = amount(row["invoice_amount"])
    offered_rate = rate(row["offered_rate_pct"])

    # Final locked policy uses a 0.5 percentage-point grid.
    valid_grid = offered_rate in {0.5, 1.0, 1.5}

    if not valid_grid:
        violations.append("rate_not_on_0.5_percent_grid")

    # Tier is not stored in the historical offer file, so tier-specific
    # caps cannot be reconstructed safely from this file alone.
    # Therefore we only validate the universal rate ceiling here.
    if offered_rate > 1.5:
        violations.append("rate_above_global_max_1.5_percent")

    # Existing offer history is demonstration data, so invoice amount
    # is retained as historical information rather than re-generated.
    if invoice_amount <= 0:
        violations.append("invalid_invoice_amount")

    return violations


def main():
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    with SOURCE_FILE.open(
        "r",
        newline="",
        encoding="utf-8-sig",
    ) as source:
        reader = csv.DictReader(source)
        rows = list(reader)

    valid_rows = [
        row for row in rows
        if row["timeline_valid"].strip() == "1"
    ]

    output_rows = []

    for row in valid_rows:
        violations = check_policy(row)

        payload = {
            "data_origin": DATA_ORIGIN,
            "ml_use_allowed": 0,
            "original_approver": row["approved_by"] or None,
            "original_approver_role": row["approver_role"] or None,
            "original_recommended_by": row["recommended_by"] or None,
            "policy_note": (
                "Historical/simulated demonstration offer. "
                "Not generated by the final production policy and "
                "must not be used for ML training or tuning."
            ),
        }

        output_row = dict(row)

        # Preserve historical approver information only inside the payload.
        output_row["approved_by"] = ""

        output_row["policy_compliant"] = int(len(violations) == 0)
        output_row["policy_violations"] = ";".join(violations)
        output_row["data_origin"] = DATA_ORIGIN
        output_row["ml_use_allowed"] = 0
        output_row["recommendation_payload"] = json.dumps(
            payload,
            separators=(",", ":"),
        )

        output_rows.append(output_row)

    fieldnames = list(output_rows[0].keys())

    with OUTPUT_FILE.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as output:
        writer = csv.DictWriter(output, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(output_rows)

    compliant = sum(
        row["policy_compliant"] == 1
        for row in output_rows
    )

    print(f"Source offers: {len(rows)}")
    print(f"Timeline-valid offers kept: {len(output_rows)}")
    print(f"Timeline-invalid offers excluded: {len(rows) - len(output_rows)}")
    print(f"Policy-compliant offers: {compliant}")
    print(f"Policy-noncompliant offers: {len(output_rows) - compliant}")
    print(f"Output: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
